package com.example.bjj.model;

public enum Position {
  CLOSED_GUARD, OPEN_GUARD, HALF_GUARD_TOP, HALF_GUARD_BOTTOM,
  SIDE_CONTROL_TOP, SIDE_CONTROL_BOTTOM, MOUNT_TOP, MOUNT_BOTTOM,
  BACK_CONTROL_TOP, TURTLE_TOP, TURTLE_BOTTOM, STANDING
}
