spring:
  datasource:
    url: jdbc:h2:mem:bjj;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: warn
